export const LIST_POPULER_PRODUCTS = [
    {
        id: 1,
        name: "Jagung Pipil Kering Grade A",
        image: "/product.jpg",
        price: 8500,
        unit: "per Kg",
        sold: 320,
        store: "Kios Tani Makmur",
        location: "Grobogan, Jawa Tengah",
        badge: "Populer",
    },
    {
        id: 2,
        name: "Benih Jagung Hibrida Pioneer P32",
        image: "/product.jpg",
        price: 150000,
        unit: "per Pack",
        sold: 110,
        store: "Sentra Jagung Nusantara",
        location: "Pati, Jawa Tengah",
        badge: "Unggulan",
    },
    {
        id: 3,
        name: "Jagung Manis Segar",
        image: "/product.jpg",
        price: 7000,
        unit: "per Kg",
        sold: 450,
        store: "Jagung Subur Abadi",
        location: "Blora, Jawa Tengah",
        badge: "Populer",
    },
    {
        id: 4,
        name: "Jagung Pakan Ternak",
        image: "/product.jpg",
        price: 6800,
        unit: "per Kg",
        sold: 290,
        store: "Toko Hasil Panen Sejahtera",
        location: "Demak, Jawa Tengah",
        badge: "Populer",
    },
    {
        id: 5,
        name: "Jagung Organik Lokal",
        image: "/product.jpg",
        price: 10000,
        unit: "per Kg",
        sold: 150,
        store: "Kios Petani Berkah",
        location: "Kudus, Jawa Tengah",
        badge: "Unggulan",
    },
];