export const LIST_FOR_YOU = [
    {
        id: 1,
        name: "Jagung Pipil Kering Grade A",
        slugProduct: "jagung-pipil-kering-grade-a",
        image: "/product.jpg",
        price: 8500,
        unit: "per Kg",
        store: "Kios Tani Makmur",
        slugStore: "kios-tani-makmur",
        location: "Kudus, Jawa Tengah",
        sold: 320
    },
    {
        id: 2,
        name: "Benih Jagung Hibrida Pioneer P32",
        slugProduct: "benih-jagung-hibrida-pioneer-p32",
        image: "/product.jpg",
        price: 150000,
        unit: "per Pack",
        store: "Sentra Jagung Nusantara",
        slugStore: "sentra-jagung-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 85
    },
    {
        id: 3,
        name: "Jagung Manis Segar Lokal",
        slugProduct: "jagung-manis-segar-lokal",
        image: "/product.jpg",
        price: 7000,
        unit: "per Kg",
        store: "Jagung Subur Abadi",
        slugStore: "jagung-subur-abadi",
        location: "Sleman, Yogyakarta",
        sold: 450
    },
    {
        id: 4,
        name: "Jagung Pakan Ternak Berkualitas",
        slugProduct: "jagung-pakan-ternak-berkualitas",
        image: "/product.jpg",
        price: 6800,
        unit: "per Kg",
        store: "Toko Hasil Panen Sejahtera",
        slugStore: "toko-hasil-panen-sejahtera",
        location: "Blitar, Jawa Timur",
        sold: 610,
    },
    {
        id: 5,
        name: "Jagung Organik Premium",
        slugProduct: "jagung-organik-premium",
        image: "/product.jpg",
        price: 10000,
        unit: "per Kg",
        store: "Kios Petani Berkah",
        slugStore: "kios-petani-berkah",
        location: "Boyolali, Jawa Tengah",
        sold: 140
    },
    {
        id: 6,
        name: "Benih Jagung Bisi 18",
        slugProduct: "benih-jagung-bisi-18",
        image: "/product.jpg",
        price: 120000,
        unit: "per Pack",
        store: "Sentra Jagung Nusantara",
        slugStore: "sentra-jagung-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 70
    },
    {
        id: 7,
        name: "Jagung Premium Siap Tanam",
        slugProduct: "jagung-premium-siap-tanam",
        image: "/product.jpg",
        price: 9500,
        unit: "per Kg",
        store: "Jagung Tani Subur",
        slugStore: "jagung-tani-subur",
        location: "Ngawi, Jawa Timur",
        sold: 390
    },
    {
        id: 8,
        name: "Jagung Super Lokal Grobogan",
        slugProduct: "jagung-super-lokal-grobogan",
        image: "/product.jpg",
        price: 8700,
        unit: "per Kg",
        store: "Kios Jagung Jaya",
        slugStore: "kios-jagung-jaya",
        location: "Grobogan, Jawa Tengah",
        sold: 510
    },
    {
        id: 9,
        name: "Jagung Kupas Siap Masak",
        slugProduct: "jagung-kupas-siap-masak",
        image: "/product.jpg",
        price: 11500,
        unit: "per Kg",
        store: "Toko Petani Mandiri",
        slugStore: "toko-petani-mandiri",
        location: "Magelang, Jawa Tengah",
        sold: 200
    },
    {
        id: 10,
        name: "Jagung Manis Organik",
        slugProduct: "jagung-manis-organik",
        image: "/product.jpg",
        price: 10500,
        unit: "per Kg",
        store: "Kios Jagung Berkah",
        slugStore: "kios-jagung-berkah",
        location: "Klaten, Jawa Tengah",
        sold: 180
    },
    {
        id: 11,
        name: "Jagung Biji Kering Pilihan",
        slugProduct: "jagung-biji-kering-pilihan",
        image: "/product.jpg",
        price: 8300,
        unit: "per Kg",
        store: "Sentra Jagung Nusantara",
        slugStore: "sentra-jagung-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 410
    },
    {
        id: 12,
        name: "Benih Jagung Manis Unggul",
        slugProduct: "benih-jagung-manis-unggul",
        image: "/product.jpg",
        price: 135000,
        unit: "per Pack",
        store: "Toko Tani Sejahtera",
        slugStore: "toko-tani-sejahtera",
        location: "Pati, Jawa Tengah",
        sold: 95
    },
    {
        id: 13,
        name: "Jagung Panen Lokal Terbaik",
        slugProduct: "jagung-panen-lokal-terbaik",
        image: "/product.jpg",
        price: 9200,
        unit: "per Kg",
        store: "Jagung Subur Abadi",
        slugStore: "jagung-subur-abadi",
        location: "Sleman, Yogyakarta",
        sold: 275
    },
    {
        id: 14,
        name: "Jagung Bisi Super Grade A",
        slugProduct: "jagung-bisi-super-grade-a",
        image: "/product.jpg",
        price: 8900,
        unit: "per Kg",
        store: "Kios Petani Mandiri",
        slugStore: "kios-petani-mandiri",
        location: "Wonogiri, Jawa Tengah",
        sold: 350
    },
    {
        id: 15,
        name: "Jagung Premium Export Quality",
        slugProduct: "jagung-premium-export-quality",
        image: "/product.jpg",
        price: 12500,
        unit: "per Kg",
        store: "Toko Jagung Nusantara",
        slugStore: "toko-jagung-nusantara",
        location: "Demak, Jawa Tengah",
        sold: 210
    },
    {
        id: 16,
        name: "Jagung Siap Panen Pati",
        slugProduct: "jagung-siap-panen-pati",
        image: "/product.jpg",
        price: 8800,
        unit: "per Kg",
        store: "Kios Pangan Rakyat",
        slugStore: "kios-pangan-rakyat",
        location: "Pati, Jawa Tengah",
        sold: 390
    },
    {
        id: 17,
        name: "Benih Jagung Tahan Hama",
        slugProduct: "benih-jagung-tahan-hama",
        image: "/product.jpg",
        price: 140000,
        unit: "per Pack",
        store: "Toko Tani Berkah",
        slugStore: "toko-tani-berkah",
        location: "Boyolali, Jawa Tengah",
        sold: 60
    },
    {
        id: 18,
        name: "Jagung Lokal Pati Unggul",
        slugProduct: "jagung-lokal-pati-unggul",
        image: "/product.jpg",
        price: 8600,
        unit: "per Kg",
        store: "Kios Jagung Lestari",
        slugStore: "kios-jagung-lestari",
        location: "Pati, Jawa Tengah",
        sold: 425
    },
    {
        id: 19,
        name: "Jagung Kupas Manis Segar",
        slugProduct: "jagung-kupas-manis-segar",
        image: "/product.jpg",
        price: 11200,
        unit: "per Kg",
        store: "Toko Pangan Mandiri",
        slugStore: "toko-pangan-mandiri",
        location: "Kudus, Jawa Tengah",
        sold: 190
    },
    {
        id: 20,
        name: "Jagung Hibrida Petani Lokal",
        slugProduct: "jagung-hibrida-petani-lokal",
        image: "/product.jpg",
        price: 9400,
        unit: "per Kg",
        store: "Jagung Tani Subur",
        slugStore: "jagung-tani-subur",
        location: "Ngawi, Jawa Timur",
        sold: 375
    },
    {
        id: 21,
        name: "Jagung Siap Tanam Terbaik",
        slugProduct: "jagung-siap-tanam-terbaik",
        image: "/product.jpg",
        price: 9000,
        unit: "per Kg",
        store: "Kios Jagung Pati",
        slugStore: "kios-jagung-pati",
        location: "Pati, Jawa Tengah",
        sold: 310
    },
    {
        id: 22,
        name: "Jagung Organik Grade Premium",
        slugProduct: "jagung-organik-grade-premium",
        image: "/product.jpg",
        price: 11000,
        unit: "per Kg",
        store: "Toko Hasil Panen",
        slugStore: "toko-hasil-panen",
        location: "Blitar, Jawa Timur",
        sold: 165
    },
    {
        id: 23,
        name: "Jagung Pakan Ternak Berkualitas",
        slugProduct: "jagung-pakan-ternak-berkualitas",
        image: "/product.jpg",
        price: 6900,
        unit: "per Kg",
        store: "Kios Petani Jaya",
        slugStore: "kios-petani-jaya",
        location: "Magetan, Jawa Timur",
        sold: 500
    },
    {
        id: 24,
        name: "Benih Jagung Manis Export",
        slugProduct: "benih-jagung-manis-export",
        image: "/product.jpg",
        price: 155000,
        unit: "per Pack",
        store: "Sentra Tani Nusantara",
        slugStore: "sentra-tani-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 40
    },
    {
        id: 25,
        name: "Jagung Manis Segar Premium",
        slugProduct: "jagung-manis-segar-premium",
        image: "/product.jpg",
        price: 10800,
        unit: "per Kg",
        store: "Jagung Subur Nusantara",
        slugStore: "jagung-subur-nusantara",
        location: "Blora, Jawa Tengah",
        sold: 330
    },
    {
        id: 26,
        name: "Jagung Pipil Super Lokal",
        slugProduct: "jagung-pipil-super-lokal",
        image: "/product.jpg",
        price: 8700,
        unit: "per Kg",
        store: "Toko Jagung Mandiri",
        slugStore: "toko-jagung-mandiri",
        location: "Demak, Jawa Tengah",
        sold: 470
    },
    {
        id: 27,
        name: "Jagung Pati Siap Konsumsi",
        slugProduct: "jagung-pati-siap-konsumsi",
        image: "/product.jpg",
        price: 9100,
        unit: "per Kg",
        store: "Kios Pangan Nusantara",
        slugStore: "kios-pangan-nusantara",
        location: "Pati, Jawa Tengah",
        sold: 380
    },
    {
        id: 28,
        name: "Jagung Export Quality",
        slugProduct: "jagung-export-quality",
        image: "/product.jpg",
        price: 13000,
        unit: "per Kg",
        store: "Jagung Lestari Mandiri",
        slugStore: "jagung-lestari-mandiri",
        location: "Bojonegoro, Jawa Timur",
        sold: 150
    },
    {
        id: 29,
        name: "Benih Jagung Unggul Tahan Cuaca",
        slugProduct: "benih-jagung-unggul-tahan-cuaca",
        image: "/product.jpg",
        price: 145000,
        unit: "per Pack",
        store: "Toko Tani Sejahtera",
        slugStore: "toko-tani-sejahtera",
        location: "Pati, Jawa Tengah",
        sold: 50
    },
    {
        id: 30,
        name: "Jagung Lokal Pilihan Grobogan",
        slugProduct: "jagung-lokal-pilihan-grobogan",
        image: "/product.jpg",
        price: 8700,
        unit: "per Kg",
        store: "Kios Jagung Nusantara",
        slugStore: "kios-jagung-nusantara",
        location: "Grobogan, Jawa Tengah",
        sold: 490
    }
]